name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"      # chạy mỗi ngày 00:00 UTC
  workflow_dispatch:          # cho phép Run workflow thủ công

permissions:
  contents: write             # cần quyền push branch 'output'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: phudammelaptrinh
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake-light.svg?palette=github-light

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
